import streamlit as st
import requests


'''
# Deepfake text detection 💡

## Generated by AI or human-written ?🤔

'''


def get_results(model_name, input_text):
    base_url = 'https://deepfake-ugp33vl5fa-ew.a.run.app/predict'

    params = {
        'model': model_name,
        'X': input_text
    }

    response = requests.get(base_url, params=params)

    if response.status_code != 200:
        return st.write("Invalid request")

    result = response.json()

    return result


st.markdown('<link rel="stylesheet" href="custom.css">', unsafe_allow_html=True)

st.session_state['button1'] = True

#text1 = st.text_input('Text ',
                          #value = "Over the past decade, rugby has seen substantial growth both on and off the field, with an increasing number of players participating worldwide. This expansion has sparked a rising interest in the science of rugby, particularly in relation to players' physical preparation. The annual count of rugby-related publications in the fields of sports science and sports medicine has seen a significant rise in recent years.From 2004 to 2023, PubMed featured nearly 4,000 studies using 'rugby' as a keyword. Out of these, approximately 44% (around 1,700 studies) focused on injuries, while only 11% pertained to physical fitness. Examining 'rugby sevens' during the same period, we found 330 studies available. Among these, 35% (approximately 115 studies) concentrated on injury-related aspects, with around 12% (roughly 40 studies) exploring fitness-related topics. It's important to note that the majority of rugby sevens studies emerged after 2009, coinciding with the inclusion of this format in the summer Olympic Games, starting with Rio 2016. Clearly, there exists a pressing demand for further high-quality research in the domain of rugby, particularly concerning physical fitness, training techniques, and conditioning.")
#st.write(f"<p style='text-align: justify;'><i>Text 1: {text1}</i></p>", unsafe_allow_html=True)

#new_text = st.text_input('Change Text 1 (here IA)', value='')

# Display the text area with the updated text

text1 = st.text_area('Enter text',
                          value = "The rugby cup is an international tournament featuring top national teams vying for the coveted Webb Ellis Trophy. It showcases intense physicality, strategic gameplay, and a strong sense of camaraderie among players.",
                          height=100)


if st.button("Predict text"):

    #ml_multi1, dl_cnn1, dl_lstm1, dl_gru1, dl_bert1 = get_results(text1)
    #st.write(f"Multinomial : {ml_multi1}%")
    #st.write(f"CNN : {dl_cnn1}%")
    #st.write(f"Multinomial : {dl_lstm1}%")
    #st.write(f"Multinomial : {dl_gru1}%")
    #st.write(f"Multinomial : {dl_bert1}%")
    # Créez trois colonnes de largeur égale
    st.session_state['button1'] = True
    st.session_state['CNN_pred_1'] = list(get_results('CNN',text1).items())
    st.session_state['LSTM_pred_1'] =list( get_results('LSTM',text1).items())
    st.session_state['gru_pred_1'] = list(get_results('GRU',text1).items())



if st.session_state['button1'] == True:


    subcol1, subcol2, subcol3 = st.columns(3)
    # Utilisez Markdown pour centrer les titres
    with subcol1:

        if 'CNN_pred_1' in st.session_state:

            st.markdown("<h2 style='text-align:center;'>CNN</h2>", unsafe_allow_html=True)
            st.image("https://i.postimg.cc/4N0vWLPf/CNN.jpg")
            st.markdown(f"<h4 style='text-align:center;'>{st.session_state['CNN_pred_1'][0][0]} ({round(st.session_state['CNN_pred_1'][0][1],2)*100}%)</h4>", unsafe_allow_html=True)


    with subcol2:

        if 'LSTM_pred_1' in st.session_state:

            st.markdown("<h2 style='text-align:center;'>LSTM</h2>", unsafe_allow_html=True)
            st.image("https://i.postimg.cc/VLvQjpSK/59908721-escargot-fun.jpg")
            st.markdown(f"<h4 style='text-align:center;'>{st.session_state['LSTM_pred_1'][0][0]} ({round(st.session_state['LSTM_pred_1'][0][1],2)*100}%)</h4>", unsafe_allow_html=True)

    with subcol3:

        if 'gru_pred_1' in st.session_state:

            st.markdown("<h2 style='text-align:center;'>GRU</h2>", unsafe_allow_html=True)
            st.image("https://www.zupimages.net/up/23/36/iryz.jpg")
            st.markdown(f"<h4 style='text-align:center;'>{st.session_state['gru_pred_1'][0][0]} ({round(st.session_state['gru_pred_1'][0][1],2)*100}%)</h4>", unsafe_allow_html=True)

    # dl_cnn2, dl_lstm2, dl_gru2 = get_results(text1)
